### ISSUE TITLE
Does not like SSR

### ISSUE THREAD

**Issue by Bouncey** [MarkoCen/react-blur-image-loader#2]
```sh
ReferenceError: window is not defined
    at /home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:19644
    at /home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:19596
    at module.exports (/home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:20321)
    at Object.defineProperty.value (/home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:5852)
    at __webpack_require__ (/home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:603)
    at Object.content (/home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:6167)
    at __webpack_require__ (/home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:603)
    at /home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:1341
    at /home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:1386
    at installedModules (/home/stuart/ctink/node_modules/react-blur-image-loader/build/reactBlurImageLoader.js:1:90)
```

**Comment by vanya2h** [comment]
+1 Request 
Need answer how to SSR

**Comment by HiradRoshandel** [comment]
+1

**Comment by dav-is** [comment]
+ another 1
